//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stimulacije_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class StimulacijaLOGIN
    {
        public int idLogin { get; set; }
        public string korime { get; set; }
        public string sifra { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
    }
}
